on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - name: ⚙️ Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: ⚙️ Start Android Emulator
      run: |
        export PATH="$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
      
        echo "Installing system image"
        echo "y" | sdkmanager "system-images;android-35;google_apis;x86_64"
        echo "Setting ANDROID_AVD_HOME"
        export ANDROID_AVD_HOME=$HOME/.config/.android/avd
        echo "Creating AVD"
        echo "no" | avdmanager create avd -n test_emulator -k "system-images;android-35;google_apis;x86_64" --device "pixel_7" --force
        echo "Starting emulator"
        emulator -avd test_emulator -no-audio -no-boot-anim -no-window -no-snapshot &
    
    - name: ⚙️ Wait for Android Emulator to complete booting
      run: |
        export PATH="$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
        adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 5; done; input keyevent 82'

    - name: Create screenshot
      run: |
        export PATH="$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH"
        adb exec-out screencap -p > screenshot.png
    
    - name: Upload screenshot
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: AndroidScreenshot
        if-no-files-found: ignore
        path: |
          ./