name: Create artifacts

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
    - shell: bash
      run: |
        expr 3 + 7 > math-homework.txt
        
    - name: Upload math result for job 1
      uses: actions/upload-artifact@v4
      with:
        name: homework_pre
        path: math-homework.txt

  job_2:
    name: Read artifact
    needs: job_1
    runs-on: ubuntu-latest
    steps:
    - name: Download math result for job 1
      uses: actions/download-artifact@v4
      with:
        name: homework_pre

    - shell: bash
      run: |
        pwd
        cat math-homework.txt
