name: Download artifacts

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  job_1:
    name: Read artifact
    runs-on: ubuntu-latest
    
    permissions:
      actions: read
      contents: read

    steps:            
    - name: Checkout repository
      uses: actions/checkout@v4

    # - name: Install GitHub CLI
    #   run: sudo apt-get install gh -y

    # - name: Authenticate GitHub CLI
    #   run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Get latest successful run ID
      id: get_run
      run: |
        RUN_ID=$(gh run list \
          --workflow=".github/workflows/CreateArtifacts.yml" \
          --branch=main \
          --json databaseId,status,conclusion \
          --jq '.[] | select(.conclusion=="success") | .databaseId' \
          | head -n 1)
        echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        echo "run_id=$RUN_ID"

    - name: Download artifact from other workflow run
      run: |
        gh run download ${{ steps.get_run.outputs.run_id }} --name="artifact-name" --dir=./downloaded-artifacts

    - shell: bash
      run: |
        pwd
        cat ./downloaded-artifacts/math-homework.txt